### PR TITLE
html render redo

### PR DESCRIPTION
**Pull request by Charlie-England**
Hey I adjusted this the best I could, there are still some problems with it but I fixed some errors and added indentation.

### CODE REVIEW

**Comment by nairraghav** [comment]
Hi Charlie,

I'm having some trouble running this code with a Syntax error which I'm not able to sort out. Looking through the file, it looks like you have the idea down so I will give you credit for completing most of the assignment.

Thanks,
Ron

**Comment by Charlie-England** [comment]
Thanks! But that's weird, I just re-ran it on my end and didn't get one. The tests were the only part I didn't mess with due to time. Still working on getting the hang of test-driven development ;)

**Comment by nairraghav** [comment]
Very weird, would you be able to copy an image here of your functional html_render? I can give more credit, perhaps I have an error on my end.

**Comment by Charlie-England** [comment]
html_outpt

**Comment by Charlie-England** [comment]
C:\Users\Charlie\OneDrive\UWPCE\SP_2019_210A_classroom\students\charlie_england\session07\html_render.py

**Comment by nairraghav** [comment]
Strange, well it looks like its working! Double check that you've committed and pushed all your changes. I will give credit in the meantime, thanks Charlie!

**Comment by Charlie-England** [comment]
The only one that git recognized as changed was run_html_render.py so I'll submit another pull request.

**Comment by Charlie-England** [comment]
Nothing was changed with that file actually (only an extra line at the end with no code), I'm interested in seeing where the error is if nothing else. Which file are you running that's giving you the syntax error?

**Pull request merged**
