### PR TITLE
another 

### PR DESCRIPTION
**Pull request by jchando1**
asdf

### CODE REVIEW

**Review by brydavis — APPROVED** [review]
looks good, it worked!

**Comment by nairraghav** [comment]
This is a great start! Please make sure you add examples to cause the other Errors:

- TypeError
- SyntaxError
- AttributeError

**Comment by PythonCHB** [comment]
Once you add the other errors, you can commit that, do a git push, and it will automatically be added to this PR.

We'll merge when you have all four errors.

**Comment by PythonCHB** [comment]
All looks good.

**Pull request merged**
